---

- name: Check if the OSI file exists and Create the properties
  hosts: play_group
  gather_facts: false
  become: yes
  roles:
    - check_file_and_gen_prop

- name: Create the properties file and script to run
  hosts: localhost
  gather_facts: false
  become: yes
  tasks:

    - name: Run the script
      include_role:
        - name: prov_single_inst
          tasks_from: step1.yml

- name: Write a mesage to OSI file
  hosts: play_group
  gather_facts: false
  become: yes
  roles:
    - write_to_OSI_bin

- name: Create script file
  hosts: localhosts
  gather_facts: false
  tasks:

    - name: create the script
      include_role:
        - name: prov_single_inst
          tasks_from: step1.yml

- name: Write message to OSI binary file
  hosts: play_group
  gather_facts: false
  become: yes
  tasks:

    - name: Gather min facts
      setup:
        gather_subset:
          - min
    
    - name: Call the role
      include_role:
        - name: prov_single_inst
          tasks_from: step2.yml

- name: Install binaries
  hosts: localhost
  tasks:

    - name: Install binaries
      include_role:
        - name: prov_single_inst
          tasks_from: step3.yml
