---

- name: Check if file OSI-BINARIES-INSTALLED exists
  stat:
    path: "{{ OSI_BIN_PATH }}"
  register: osi_bin_file_stat

- name: set fact
  set_fact:
    osi_file_exists: "{{ osi_bin_file_stat.stat.exists }}"

- name: If OSI binaries does not exists
  when: not osi_file_exists
  vars:          
    template_prop: "{% if ORACLE_VERSION == '12CR2' %}12cr2_Single_Instance_Database.properties.Jul2018.TEMPLATE{% endif %}"
    template_script: "{% if ORACLE_VERSION == '12CR2' %}12cr2_Single_Instance_Provisioning.sh.TEMPLATE{% endif %}"
  command: "/bin/cat/ {{ OMS_DIR }}/{{ template_prop }} |sed \"s#%%TARGET_HOST%%#{{ inventory_hostname }}#\" > {{ OMS_WORKDIR }}/{{ prop_file }}"
  delegate_to: localhost